---
- name: "Create Logical Volume for mount: {{ mount }}"
  lvol:
    vg: "{{ satellite_vg }}"
    lv: "{{ lv }}"
    size: "{{ size }}"
    force: yes

- name: "Create File System for mount: {{ mount }}"
  filesystem:
    fstype: xfs
    dev: "/dev/{{ satellite_vg }}/{{ lv }}"

- name: "Create Mount: {{ mount }}"
  mount:
    name: "{{ mount }}"
    src: "/dev/{{ satellite_vg }}/{{ lv }}"
    fstype: xfs
    dump: 1
    passno: 2
    state: mounted
