---
- name: Repositories | Get currently enabled repositories
  rhsm_repository:
    state: list_enabled
  register: enabled_repositories

- name: Repositories | Disable non-required repositories
  rhsm_repository:
    name: "{{ item }}"
    state: disabled
  with_items: "{{
    enabled_repositories.repositories |
    map(attribute='id') | list |
    difference(repositories) }}"

- name: Repositories | Enabled required repositories
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repositories }}"
