---
- name: Satellite Register | Register Manually | Install katello-ca-consumer
  yum:
    name: http://{{ satellite_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm
    validate_certs: "{{ satellite_validate_certs | default(True) }}"
    state: present
    
- name: Satellite Register | Register Manually | Register with Subscription Manager
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activation_key }}"
    org_id: "{{ satellite_org }}"
  register: 'registration_return'
    
- name: Satellite Register | Register Manually | Install katello-agent
  yum:
    name: katello-agent
    state: latest
  when: registration_return is success

- name: Satellite Register | Register Manually | Start and Enable goferd
  service:
    name: goferd
    enabled: yes
    state: started
